<?php

namespace Database\Seeders;

use App\Models\JobListing;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        JobListing::truncate();

        JobListing::insert([
            [
                'title' => 'Restaurant Supervisor',
                'slug' => 'restaurant-supervisor',
                'location' => 'Lusaka, Zambia',
                'type' => 'full-time',
                'department' => 'Operations',
                'summary' => 'We are seeking an experienced and customer-focused Restaurant Supervisor to join our team. The successful candidate will oversee daily restaurant operations, manage a team of waiters and servers, and ensure exceptional customer service. The ideal candidate will have a passion for delivering outstanding dining experiences and possess excellent leadership, communication, and problem-solving skills.',
                'description' => "Job Overview\n\nWe are seeking an experienced and customer-focused Restaurant Supervisor to join our team. The successful candidate will oversee daily restaurant operations, manage a team of waiters and servers, and ensure exceptional customer service. The ideal candidate will have a passion for delivering outstanding dining experiences and possess excellent leadership, communication, and problem-solving skills.\n\nKey Responsibilities\n\nStaff Management\n\n- Supervise and coordinate a team of waiters, servers, and hosts/hostesses.\n- Train, coach, and mentor staff to improve performance and customer service skills.\n- Conduct performance evaluations and provide constructive feedback.\n- Address staff concerns and resolve conflicts in a fair and timely manner.\n\nCustomer Service\n\n- Ensure exceptional customer service and satisfaction.\n- Greet and interact with customers, responding promptly to their needs and concerns.\n- Resolve customer complaints and issues professionally and efficiently.\n- Foster a positive and welcoming atmosphere in the restaurant.\n\nOperations\n\n- Oversee daily restaurant operations, including opening and closing procedures.\n- Monitor table management, seating, and wait times.\n- Ensure compliance with health and safety regulations, and maintain a clean and organized environment.\n- Manage inventory, supplies, and equipment.\n\nSales and Revenue\n\n- Monitor sales and revenue growth, identifying opportunities to increase revenue.\n- Implement promotions and upselling strategies to drive sales.\n- Analyze customer feedback and implement changes to improve sales and customer satisfaction.\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Restaurant Supervisor Application\" in the subject line",
                'requirements' => json_encode([
                    '2-3 years of experience in a supervisory role in the food and beverage industry.',
                    'Proven experience managing a team of waiters, servers, and hosts/hostesses.',
                    'Excellent leadership, communication, and problem-solving skills.',
                    'Strong customer service and conflict resolution skills.',
                    'Ability to work in a fast-paced environment and prioritize tasks effectively.',
                    'Basic math skills and accuracy with handling cash and operating a point-of-sale system.',
                    'High school certificate or equivalent required; hospitality or food service management certification preferred.',
                    'Availability to work flexible hours, including evenings, weekends, and holidays.',
                    'Ability to stand for long periods and move quickly throughout the restaurant.',
                    'Ability to lift up to 25 pounds and carry trays with food and beverages.',
                    'Knowledge of food and beverage operations, including menu planning and inventory management.',
                    'Familiarity with restaurant management software and point of sale systems.',
                    'Multilingual skills (optional).',
                ]),
                'responsibilities' => json_encode([
                    'Supervise and coordinate a team of waiters, servers, and hosts/hostesses.',
                    'Train, coach, and mentor staff to improve performance and customer service skills.',
                    'Conduct performance evaluations and provide constructive feedback.',
                    'Address staff concerns and resolve conflicts in a fair and timely manner.',
                    'Ensure exceptional customer service and satisfaction.',
                    'Greet and interact with customers, responding promptly to their needs and concerns.',
                    'Resolve customer complaints and issues professionally and efficiently.',
                    'Foster a positive and welcoming atmosphere in the restaurant.',
                    'Oversee daily restaurant operations, including opening and closing procedures.',
                    'Monitor table management, seating, and wait times.',
                    'Ensure compliance with health and safety regulations, and maintain a clean and organized environment.',
                    'Manage inventory, supplies, and equipment.',
                    'Monitor sales and revenue growth, identifying opportunities to increase revenue.',
                    'Implement promotions and upselling strategies to drive sales.',
                    'Analyze customer feedback and implement changes to improve sales and customer satisfaction.',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-10-03',
                'is_active' => true,
            ],
            [
                'title' => 'Business Development',
                'slug' => 'business-development',
                'location' => 'Mansa / Serenje, Zambia',
                'type' => 'full-time',
                'department' => 'Business Development',
                'summary' => 'Falane Solutions is seeking a motivated and results-driven Business Development professional to join our team. The successful candidate will be responsible for identifying and developing growth opportunities, building client relationships, and contributing to our business expansion strategy. This position requires a combination of sales expertise, market knowledge, and excellent communication skills.',
                'description' => "Job Overview\n\nFalane Solutions is seeking a motivated and results-driven Business Development professional to join our team. The successful candidate will be responsible for identifying and developing growth opportunities, building client relationships, and contributing to our business expansion strategy. This position requires a combination of sales expertise, market knowledge, and excellent communication skills.\n\nKey Responsibilities\n\n- Develop a growth strategy focused both on financial gain and customer satisfaction\n- Conduct research to identify new markets and customer needs\n- Arrange business meetings with prospective clients\n- Promote the company's products/services addressing or predicting clients' objectives\n- Prepare sales contracts ensuring adherence to law-established rules and guidelines\n- Keep records of sales, revenue, invoices\n- Build long-term relationships with new and existing customers\n- Develop entry level staff into valuable salespeople\n\nRequirements and Skills\n\n- Proven working experience as a business development manager, sales executive or a relevant role\n- Proven sales track record\n- Experience in customer support is a plus\n- Proficiency in MS Office and CRM software (e.g. Salesforce)\n- Proficiency in English\n- Market knowledge\n- Communication and negotiation skills\n- Ability to build rapport\n- Time management and planning skills\n\nQualifications\n\n- Grade 12 school certificate\n- BSc/BA in business administration, sales or relevant field\n- 1-2 years work experience\n- Good communication skills\n- Strong oral and writing skills\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Business Development Application\" in the subject line",
                'requirements' => json_encode([
                    'Proven working experience as a business development manager, sales executive or a relevant role',
                    'Proven sales track record',
                    'Experience in customer support is a plus',
                    'Proficiency in MS Office and CRM software (e.g. Salesforce)',
                    'Proficiency in English',
                    'Market knowledge',
                    'Communication and negotiation skills',
                    'Ability to build rapport',
                    'Time management and planning skills',
                    'Grade 12 school certificate',
                    'BSc/BA in business administration, sales or relevant field',
                    '1-2 years work experience',
                    'Good communication skills',
                    'Strong oral and writing skills',
                ]),
                'responsibilities' => json_encode([
                    'Develop a growth strategy focused both on financial gain and customer satisfaction',
                    'Conduct research to identify new markets and customer needs',
                    'Arrange business meetings with prospective clients',
                    'Promote the company\'s products/services addressing or predicting clients\' objectives',
                    'Prepare sales contracts ensuring adherence to law-established rules and guidelines',
                    'Keep records of sales, revenue, invoices',
                    'Build long-term relationships with new and existing customers',
                    'Develop entry level staff into valuable salespeople',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-10-01',
                'is_active' => true,
            ],
            [
                'title' => 'Mining Engineers',
                'slug' => 'mining-engineers',
                'location' => 'Mansa / Serenje, Zambia',
                'type' => 'full-time',
                'department' => 'Engineering',
                'summary' => 'Our client is looking for someone to plan, design, organize and supervise the development of mines, mine facilities, systems and equipment; to prepare and supervise the extraction of metallic or non-metallic minerals and ores from surface mines.',
                'description' => "Job Overview\n\nOur client is looking for someone to plan, design, organize and supervise the development of mines, mine facilities, systems and equipment; to prepare and supervise the extraction of metallic or non-metallic minerals and ores from surface mines.\n\nKey Responsibilities\n\n- Assessing the feasibility of new sites.\n- Managing budgets, costing and organizing supplies.\n- Training and supervising staff.\n- Liaising with and advising managerial and technical staff (geologists, surveyors etc.)\n- Ascertaining extraction risks.\n- Using specialist computer applications to maximize planning and production.\n- Monitoring and evaluating underground performance.\n- Managing and documenting the progress of mining operations and activities.\n- Compilation of reports on production, maintenance, equipment and unit costs.\n- Ensuring that operations and equipment comply with HSE requirements.\n- Planning and implementing extraction systems.\n- Working with other mine professionals, including geologists and construction staff.\n\nRequirements and Skills\n\n- Grade 12 school certificate.\n- Diploma or BEng/BSc in Mining Engineering from a recognized institution\n- Minimum of 1-2 years work experience in open pit mining\n- Member of EIZ.\n- Very good computer skills.\n- Proficient in common 3D mining software packages such as surpac, Data mine (studio RM), and Deswik.\n- Communication and negotiation skills\n- First Aid Certificate is added advantage.\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Mining Engineers Application\" in the subject line",
                'requirements' => json_encode([
                    'Grade 12 school certificate.',
                    'Diploma or BEng/BSc in Mining Engineering from a recognized institution',
                    'Minimum of 1-2 years work experience in open pit mining',
                    'Member of EIZ.',
                    'Very good computer skills.',
                    'Proficient in common 3D mining software packages such as surpac, Data mine (studio RM), and Deswik.',
                    'Communication and negotiation skills',
                    'First Aid Certificate is added advantage.',
                ]),
                'responsibilities' => json_encode([
                    'Assessing the feasibility of new sites.',
                    'Managing budgets, costing and organizing supplies.',
                    'Training and supervising staff.',
                    'Liaising with and advising managerial and technical staff (geologists, surveyors etc.)',
                    'Ascertaining extraction risks.',
                    'Using specialist computer applications to maximize planning and production.',
                    'Monitoring and evaluating underground performance.',
                    'Managing and documenting the progress of mining operations and activities.',
                    'Compilation of reports on production, maintenance, equipment and unit costs.',
                    'Ensuring that operations and equipment comply with HSE requirements.',
                    'Planning and implementing extraction systems.',
                    'Working with other mine professionals, including geologists and construction staff.',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-10-01',
                'is_active' => true,
            ],
            [
                'title' => 'Geologist',
                'slug' => 'geologist',
                'location' => 'Mansa / Serenje, Zambia',
                'type' => 'full-time',
                'department' => 'Engineering',
                'summary' => 'Our clients are seeking experienced Geologists to conduct and oversee manganese ore exploration activities. The ideal candidates should have at least 4 years of relevant experience and possess a valid exploration license. This role involves planning and executing exploration programs, analyzing geological data, and contributing to resource estimation and development.',
                'description' => "Job Overview\n\nOur clients are seeking experienced Geologists to conduct and oversee manganese ore exploration activities. The ideal candidates should have at least 4 years of relevant experience and possess a valid exploration license. This role involves planning and executing exploration programs, analyzing geological data, and contributing to resource estimation and development.\n\nKey Responsibilities\n\n- Plan and conduct geological surveys and exploration programs for manganese ore.\n- Collect and analyze geological samples, including rock, soil, and core samples.\n- Interpret geological data and generate detailed geological maps and reports.\n- Use geophysical and geochemical techniques to identify ore deposits.\n- Collaborate with mining engineers and other team members to develop exploration strategies.\n- Ensure compliance with safety, environmental, and regulatory requirements.\n- Prepare and present exploration reports and findings to management and stakeholders.\n- Maintain accurate records of exploration activities and data.\n- Use GIS, mining software, and other technological tools for data analysis and modeling.\n- Provide technical support and guidance to junior geologists and field staff.\n- Conduct magnetometer survey and IP Resistivity field tests\n- Should know how use Total Station and DGPS instruments\n\nQualifications\n\n- Bachelor's degree in Geology, Earth Sciences, or a related field. A Master's degree is preferred.\n- Minimum of 4 years of experience in mineral exploration, specifically in manganese ore.\n- Valid exploration license.\n- Proficiency in geological mapping, sampling, and data interpretation\n- Experience with geophysical and geochemical exploration techniques.\n- Strong knowledge of mining software (e.g., GIS, Surpac, Micromine).\n- Excellent analytical and problem-solving skills.\n- Strong communication and report-writing abilities.\n- Ability to work in remote locations and under challenging conditions.\n- Commitment to safety and environmental standards.\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Geologist Application\" in the subject line",
                'requirements' => json_encode([
                    'Bachelor\'s degree in Geology, Earth Sciences, or a related field. A Master\'s degree is preferred.',
                    'Minimum of 4 years of experience in mineral exploration, specifically in manganese ore.',
                    'Valid exploration license.',
                    'Proficiency in geological mapping, sampling, and data interpretation',
                    'Experience with geophysical and geochemical exploration techniques.',
                    'Strong knowledge of mining software (e.g., GIS, Surpac, Micromine).',
                    'Excellent analytical and problem-solving skills.',
                    'Strong communication and report-writing abilities.',
                    'Ability to work in remote locations and under challenging conditions.',
                    'Commitment to safety and environmental standards.',
                ]),
                'responsibilities' => json_encode([
                    'Plan and conduct geological surveys and exploration programs for manganese ore.',
                    'Collect and analyze geological samples, including rock, soil, and core samples.',
                    'Interpret geological data and generate detailed geological maps and reports.',
                    'Use geophysical and geochemical techniques to identify ore deposits.',
                    'Collaborate with mining engineers and other team members to develop exploration strategies.',
                    'Ensure compliance with safety, environmental, and regulatory requirements.',
                    'Prepare and present exploration reports and findings to management and stakeholders.',
                    'Maintain accurate records of exploration activities and data.',
                    'Use GIS, mining software, and other technological tools for data analysis and modeling.',
                    'Provide technical support and guidance to junior geologists and field staff.',
                    'Conduct magnetometer survey and IP Resistivity field tests',
                    'Should know how use Total Station and DGPS instruments',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-09-30',
                'is_active' => true,
            ],
            [
                'title' => 'Chief Claims Officer (CCO)',
                'slug' => 'chief-claims-officer',
                'location' => 'Lusaka, Zambia',
                'type' => 'full-time',
                'department' => 'Claims',
                'summary' => 'We are seeking an experienced Chief Claims Officer to lead our claims division. The successful candidate will develop and execute the overall claims strategy, oversee the entire claims process, and ensure the delivery of high-quality claims services. The ideal candidate will have extensive experience in P&C reinsurance claims management and exceptional leadership abilities.',
                'description' => "Job Overview\n\nWe are seeking an experienced and customer-focused Chief Claims Officer to join our team. The successful candidate will oversee daily claims operations, manage a team of claims professionals, and ensure exceptional service delivery. The ideal candidate will have a passion for delivering outstanding client experiences and possess excellent leadership, communication, and problem-solving skills.\n\nKey Responsibilities\n\nStrategic Leadership\n\n- Develop and execute the overall claims strategy in alignment with the company's goals and objectives.\n- Lead and inspire the claims department, ensuring the delivery of high-quality claims services.\n- Provide strategic direction and oversight to the claims team, fostering a culture of excellence and continuous improvement.\n\nClaims Management\n\n- Oversee the entire claims process, from initial intake to final resolution, ensuring efficiency and effectiveness.\n- Handle complex and high-value claims, providing expert guidance and decision-making.\n- Implement best practices and standard operating procedures to enhance claims handling.\n\nClient Engagement and Relationship Management\n\n- Enhance client satisfaction by actively engaging with clients and delivering a positive claims experience.\n- Build and maintain strong relationships with key clients, brokers, and industry stakeholders.\n- Represent the company in client meetings, industry events, and professional associations.\n\nReserving and Compliance\n\n- Ensure accurate reserving practices in compliance with IFRS 17 and other regulatory requirements.\n- Establish robust internal controls and audit mechanisms to ensure compliance and manage risks.\n- Collaborate with finance and actuarial teams to ensure accurate financial reporting and reserving.\n\nData Analysis and Reporting\n\n- Monitor and analyze claims data to identify trends, drive improvements, and support strategic decision-making.\n- Prepare and present regular reports on claims performance to the executive team and board of directors.\n- Utilize data analytics to enhance the efficiency and effectiveness of the claims function.\n\nTeam Development and Management\n\n- Mentor and develop the claims team, promoting professional growth and skill enhancement\n- Ensure adequate training and development programs are in place for all claims staff.\n- Foster a collaborative and supportive team environment.\n\nQualifications\n\n- Experience: 10+ years of experience in P&C reinsurance claims management, with significant experience in leadership roles.\n- Education: Advanced degree in insurance, law, business administration, or a related field.\n- Skills and Attributes: Exceptional leadership and strategic thinking abilities.\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Chief Claims Officer (CCO) Application\" in the subject line",
                'requirements' => json_encode([
                    'Experience: 10+ years of experience in P&C reinsurance claims management, with significant experience in leadership roles.',
                    'Education: Advanced degree in insurance, law, business administration, or a related field.',
                    'Exceptional leadership and strategic thinking abilities.',
                ]),
                'responsibilities' => json_encode([
                    'Develop and execute the overall claims strategy in alignment with the company\'s goals and objectives.',
                    'Lead and inspire the claims department, ensuring the delivery of high-quality claims services.',
                    'Provide strategic direction and oversight to the claims team, fostering a culture of excellence and continuous improvement.',
                    'Oversee the entire claims process, from initial intake to final resolution, ensuring efficiency and effectiveness.',
                    'Handle complex and high-value claims, providing expert guidance and decision-making.',
                    'Implement best practices and standard operating procedures to enhance claims handling.',
                    'Enhance client satisfaction by actively engaging with clients and delivering a positive claims experience.',
                    'Build and maintain strong relationships with key clients, brokers, and industry stakeholders.',
                    'Represent the company in client meetings, industry events, and professional associations.',
                    'Ensure accurate reserving practices in compliance with IFRS 17 and other regulatory requirements.',
                    'Establish robust internal controls and audit mechanisms to ensure compliance and manage risks.',
                    'Collaborate with finance and actuarial teams to ensure accurate financial reporting and reserving.',
                    'Monitor and analyze claims data to identify trends, drive improvements, and support strategic decision-making.',
                    'Prepare and present regular reports on claims performance to the executive team and board of directors.',
                    'Utilize data analytics to enhance the efficiency and effectiveness of the claims function.',
                    'Mentor and develop the claims team, promoting professional growth and skill enhancement',
                    'Ensure adequate training and development programs are in place for all claims staff.',
                    'Foster a collaborative and supportive team environment.',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-07-22',
                'is_active' => true,
            ],
            [
                'title' => 'Claims Manager Position',
                'slug' => 'claims-manager-position',
                'location' => 'Lusaka, Zambia',
                'type' => 'full-time',
                'department' => 'Claims',
                'summary' => 'An emerging reinsurance company is seeking a dedicated and experienced Claims Manager to join its claims department. Reporting to the Head of Claims, the Claims Manager will oversee the daily operations of the claims team, ensuring efficient and effective claims handling and resolution. The ideal candidate will have a strong background in P&C reinsurance claims and a commitment to delivering exceptional client service.',
                'description' => "Job Overview\n\nAn emerging reinsurance company is seeking a dedicated and experienced Claims Manager to join its claims department. Reporting to the Head of Claims, the Claims Manager will oversee the daily operations of the claims team, ensuring efficient and effective claims handling and resolution. The ideal candidate will have a strong background in P&C reinsurance claims and a commitment to delivering exceptional client service.\n\nKey Responsibilities\n\nClaims Handling and Resolution\n\n- Manage the end-to-end claims process, ensuring timely and accurate resolution of claims.\n- Handle complex and high-value claims, providing technical expertise and guidance to the claims team.\n- Ensure consistent application of claims policies and procedures in line with industry best practices.\n\nTeam Leadership and Development\n\n- Lead, mentor, and develop a team of claims assistants, fostering a culture of continuous improvement and professional growth.\n- Provide regular training and professional development opportunities to team members\n- Monitor team performance and implement strategies to enhance efficiency and effectiveness.\n\nClient Engagement and Relationship Management\n\n- Enhance client satisfaction by proactively managing relationships and delivering a positive claims experience.\n- Engage with key clients to understand their needs and provide tailored claims solutions.\n- Represent the claims department in client meetings and industry events.\n\nData Analysis and Reporting\n\n- Monitor and analyze claims data to identify trends, implement improvements, and support strategic decision-making.\n- Prepare regular reports on claims performance and provide insights to the Head of Claims.\n- Use data analytics to enhance the efficiency and effectiveness of the claims function.\n\nCompliance and Quality Assurance\n\n- Ensure compliance with internal policies and regulatory requirements, including IFRS 17.\n- Implement robust internal controls and audit mechanisms to maintain compliance and manage risks.\n- Collaborate with the Head of Claims to develop and update claims policies and procedures.\n\nQualifications\n\n- Experience: 5-7 years of experience in P&C reinsurance claims management.\n- Education: Bachelor's degree in insurance, law, business administration, or a related field.\n- Skills and Attributes: Strong technical expertise in P&C reinsurance claims and complex claims management, excellent team management skills, strong client engagement and relationship management skills, analytical and problem-solving abilities with a focus on data-driven decision-making, knowledge of IFRS 17 and reserving practices, strong communication and interpersonal skills.\n\nHow to Apply\n\nSend your resume and cover letter to:\n\ninfo@falanesolutions.com\n\nPlease include \"Claims Manager Position Application\" in the subject line",
                'requirements' => json_encode([
                    'Experience: 5-7 years of experience in P&C reinsurance claims management.',
                    'Education: Bachelor\'s degree in insurance, law, business administration, or a related field.',
                    'Strong technical expertise in P&C reinsurance claims and complex claims management.',
                    'Excellent team management skills.',
                    'Strong client engagement and relationship management skills.',
                    'Analytical and problem-solving abilities, with a focus on data-driven decision-making.',
                    'Knowledge of IFRS 17 and reserving practices.',
                    'Strong communication and interpersonal skills.',
                ]),
                'responsibilities' => json_encode([
                    'Manage the end-to-end claims process, ensuring timely and accurate resolution of claims.',
                    'Handle complex and high-value claims, providing technical expertise and guidance to the claims team.',
                    'Ensure consistent application of claims policies and procedures in line with industry best practices.',
                    'Lead, mentor, and develop a team of claims assistants, fostering a culture of continuous improvement and professional growth.',
                    'Provide regular training and professional development opportunities to team members',
                    'Monitor team performance and implement strategies to enhance efficiency and effectiveness.',
                    'Enhance client satisfaction by proactively managing relationships and delivering a positive claims experience.',
                    'Engage with key clients to understand their needs and provide tailored claims solutions.',
                    'Represent the claims department in client meetings and industry events.',
                    'Monitor and analyze claims data to identify trends, implement improvements, and support strategic decision-making.',
                    'Prepare regular reports on claims performance and provide insights to the Head of Claims.',
                    'Use data analytics to enhance the efficiency and effectiveness of the claims function.',
                    'Ensure compliance with internal policies and regulatory requirements, including IFRS 17.',
                    'Implement robust internal controls and audit mechanisms to maintain compliance and manage risks.',
                    'Collaborate with the Head of Claims to develop and update claims policies and procedures.',
                ]),
                'salary_range' => null,
                'closing_date' => '2024-11-30',
                'is_active' => true,
            ],
        ]);
    }
}
